POST http://localhost:3001/useradmin
Content-Type: application/json

{
    "userName": "admin2",
    "name": "admin",
    "email": "admin2@gmail.com",
    "tel": 14988048374,
    "cpf": 39693108817,
    "password": "admin",
    "confirmPassword": "admin"
}


###

POST http://localhost:3001/user
Content-Type: application/json

{
    "userName": "felipeoliveira",
    "name": "Felipe Oliveira",
    "email": "felipinho@usp.br",
    "tel": 41982736401,
    "cpf": 29364928477,
    "password": "f123",
    "confirmPassword": "f123"
}


###


GET http://localhost:3001/user


###
GET http://localhost:3001/user/64ab203eca42eb79ba01225c
###

DELETE http://localhost:3001/user/64ab26f5e144d922c52d8a56

### 
PUT http://localhost:3001/user/64ab203eca42eb79ba01225c
Content-Type: application/json
title": "title 2",
    "category": "Test 2",
    "price": 12321312321312,
    "stock": 0,
    "desc": "desc 1",
    "image1": "/public/productImages/eg_1_01.avif",
    "image2": "/public/productImages/eg_1_02.avif",
    "image3": "/public/productImages/eg_1_03.avif",
    "image4": "/public/productImages/eg_1_04.avif"
}